version: '3'
services:
  purchase:
    image: 
      pzfreo/purchase-ts:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    ports: 
      - "8000:8000"
    restart: unless-stopped
    command: ["./wait-for-it.sh", "postgres:5432", "--","npm", "run","start"]
    networks:
      - backend
    environment: 
      # DEBUG: "*:*"
      DBHOST: "postgres"
      DBUSER: "postgres"
      DBDATABASE: "postgres"
      DBPASSWORD: "mypass"
      DBPORT: 5432
      PORT: 8000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypass"
      POSTGRES_DATABASE: "postgres"
    networks:
      - backend
networks:
  backend:
    driver: bridge 
